/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Adrian, Dylan y Roberto
 */
public class CrearCalendario extends javax.swing.JFrame {

    /**
     * Creates new form lol
     */
    public CrearCalendario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jComboBoxPeriodo = new javax.swing.JComboBox();
    jButtonAceptarPeriodo = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabelTotalEvaluaciones = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabelTotalPorcentual = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea = new javax.swing.JTextArea();
    jLabel4 = new javax.swing.JLabel();
    jTextFieldDescripcionEvaluacion = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jTextFieldDia = new javax.swing.JTextField();
    jTextFieldMes = new javax.swing.JTextField();
    jTextFieldAgno = new javax.swing.JTextField();
    jTextFieldHora = new javax.swing.JTextField();
    jTextFieldMinutos = new javax.swing.JTextField();
    jTextFieldSegundos = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jTextFieldValorPorcentual = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();
    jComboBoxProfesores = new javax.swing.JComboBox();
    jLabel15 = new javax.swing.JLabel();
    jTextFieldDescripcionRubro = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jTextFieldValorRubro = new javax.swing.JTextField();
    jLabel18 = new javax.swing.JLabel();
    jButtonAgregarRubro = new javax.swing.JButton();
    jButtonVolver = new javax.swing.JButton();
    jButtonAceptarCrearCalendario = new javax.swing.JButton();
    jLabel19 = new javax.swing.JLabel();
    jLabelTotalRubros = new javax.swing.JLabel();
    jButtonAgregarEvaluacion = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("Selecciones el periodo de practica:");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

    jPanel1.add(jComboBoxPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 62, 108, -1));

    jButtonAceptarPeriodo.setText("Aceptar periodo");
    jPanel1.add(jButtonAceptarPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 61, -1, -1));

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel2.setText("Crear calendario de evaluacion");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 21, -1, -1));

    jLabel3.setText("Total de evaluaciones en este periodo:");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, -1, -1));

    jLabelTotalEvaluaciones.setText("0");
    jPanel1.add(jLabelTotalEvaluaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

    jLabel5.setText("Total porcentual entre todas las evaluaciones:");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

    jLabelTotalPorcentual.setText("0");
    jPanel1.add(jLabelTotalPorcentual, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

    jLabel8.setText("%");
    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

    jTextArea.setColumns(20);
    jTextArea.setRows(5);
    jScrollPane1.setViewportView(jTextArea);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 251, -1, -1));

    jLabel4.setText("Descripcion:");
    jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, -1, -1));

    jTextFieldDescripcionEvaluacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldDescripcionEvaluacionActionPerformed(evt);
      }
    });
    jPanel1.add(jTextFieldDescripcionEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 161, 250, -1));

    jLabel7.setText("Fecha entrega:");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
    jPanel1.add(jTextFieldDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 187, 23, -1));
    jPanel1.add(jTextFieldMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 187, 23, -1));
    jPanel1.add(jTextFieldAgno, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 187, 40, -1));
    jPanel1.add(jTextFieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 187, 23, -1));
    jPanel1.add(jTextFieldMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 187, 23, -1));
    jPanel1.add(jTextFieldSegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 187, 23, -1));

    jLabel9.setText("/");
    jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 190, -1, -1));

    jLabel10.setText("/");
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 190, -1, -1));

    jLabel11.setText(":");
    jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

    jLabel12.setText(":");
    jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 190, -1, -1));

    jLabel13.setText("Valor porcentual: ");
    jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 164, -1, -1));
    jPanel1.add(jTextFieldValorPorcentual, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 50, -1));

    jLabel14.setText("Profesor encargado: ");
    jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 228, -1, -1));

    jComboBoxProfesores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Profesor asesor", "Profesor curso" }));
    jPanel1.add(jComboBoxProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 154, -1));

    jLabel15.setText("Agregar rubro:");
    jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, -1, -1));
    jPanel1.add(jTextFieldDescripcionRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 276, 179, -1));

    jLabel16.setText("Descripcion:");
    jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 279, -1, -1));

    jLabel17.setText("Valor:");
    jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, -1, -1));
    jPanel1.add(jTextFieldValorRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 302, 82, -1));

    jLabel18.setText("%");
    jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 305, -1, -1));

    jButtonAgregarRubro.setText("Agregar rubro");
    jButtonAgregarRubro.setActionCommand("AgregarRubro");
    jPanel1.add(jButtonAgregarRubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 328, -1, -1));

    jButtonVolver.setText("Volver");
    jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVolverActionPerformed(evt);
      }
    });
    jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

    jButtonAceptarCrearCalendario.setText("Aceptar");
    jButtonAceptarCrearCalendario.setActionCommand("AceptarCrearCalendario");
    jPanel1.add(jButtonAceptarCrearCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

    jLabel19.setText("Total:");
    jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 354, -1, 20));

    jLabelTotalRubros.setText("0");
    jPanel1.add(jLabelTotalRubros, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 30, 10));

    jButtonAgregarEvaluacion.setText("Agregar evaluacion");
    jButtonAgregarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonAgregarEvaluacionActionPerformed(evt);
      }
    });
    jPanel1.add(jButtonAgregarEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

    jLabel6.setText("%");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, 30));

    jLabel21.setText("%");
    jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 20, 20));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescripcionEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionEvaluacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionEvaluacionActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAgregarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEvaluacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarEvaluacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCalendario().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton jButtonAceptarCrearCalendario;
  public javax.swing.JButton jButtonAceptarPeriodo;
  public javax.swing.JButton jButtonAgregarEvaluacion;
  public javax.swing.JButton jButtonAgregarRubro;
  public javax.swing.JButton jButtonVolver;
  public javax.swing.JComboBox jComboBoxPeriodo;
  public javax.swing.JComboBox jComboBoxProfesores;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  public javax.swing.JLabel jLabelTotalEvaluaciones;
  public javax.swing.JLabel jLabelTotalPorcentual;
  public javax.swing.JLabel jLabelTotalRubros;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  public javax.swing.JTextArea jTextArea;
  public javax.swing.JTextField jTextFieldAgno;
  public javax.swing.JTextField jTextFieldDescripcionEvaluacion;
  public javax.swing.JTextField jTextFieldDescripcionRubro;
  public javax.swing.JTextField jTextFieldDia;
  public javax.swing.JTextField jTextFieldHora;
  public javax.swing.JTextField jTextFieldMes;
  public javax.swing.JTextField jTextFieldMinutos;
  public javax.swing.JTextField jTextFieldSegundos;
  public javax.swing.JTextField jTextFieldValorPorcentual;
  public javax.swing.JTextField jTextFieldValorRubro;
  // End of variables declaration//GEN-END:variables
}
